# Generated by Django 4.1 on 2022-08-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-updated"]},
        ),
    ]
