# Generated by Django 4.1 on 2022-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="..."),
        ),
    ]
