# Generated by Django 4.1 on 2022-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profiles/nofile.png", upload_to="profiles"
            ),
        ),
    ]
